PROMPT "Adja meg az utasitas nevet: "
ACCEPT ut

SELECT LPAD(' ', 3*level)||operation||' '||options||' '||object_name terv,
  STATEMENT_ID, PLAN_ID, TIMESTAMP,  REMARKS, OPERATION, OPTIONS, OBJECT_NODE,
  OBJECT_OWNER, OBJECT_NAME, OBJECT_ALIAS, OBJECT_INSTANCE, OBJECT_TYPE, OPTIMIZER,
  SEARCH_COLUMNS, ID, PARENT_ID, DEPTH , POSITION, COST, CARDINALITY, BYTES, OTHER_TAG,
  PARTITION_START, PARTITION_STOP, PARTITION_ID, -- OTHER LONG, OTHER_XML          CLOB,
  DISTRIBUTION, CPU_COST, IO_COST, TEMP_SPACE, ACCESS_PREDICATES, FILTER_PREDICATES,
  PROJECTION, TIME, QBLOCK_NAME 
FROM PLAN_TABLE
START WITH id = 0 AND statement_id = '&&ut'
CONNECT BY PRIOR id = parent_id AND statement_id = '&&ut';
